### PR TITLE
8.0 greenify travis purchase request jne

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
- Fix some tests and pass them to python files
- I move the field `purchase_request_lines` to the `purchase_request` module level cause this fields is used into `purchase_request_to_rfq` AND `purchase_request_to_requisition` (without any dependencies between both)
- I also remove the key `analytic_account_id` from the prepared vals of the wizard.item that create purchase order from purchase request cause this value is based from the item.line_id (moreover there is no fields `analytic_account_id` defined into the wizard.item (`to_rfq` module)

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@JonathanNEMRY I don't think that adding 'purchase_request_lines' to 'purchase_order_line' in 'purchase_request' module is correct. In fact, module 'purchase_request_to_rfq' already has this field, and in 'purchase_request_to_requisition' the field with the same name belongs to 'purchase_request_line'. What do you think?

**Comment by JonathanNEMRY** [comment]
Hello @jbeficent 
here is the source code that made me took the decision to move the field `purchase_request_lines` into the module `purchase_request`
Into purchase_request_to_requisition/models/purchase_requisition.py/PurchaseRequisition

```
    @api.model
    def _prepare_purchase_order_line(self, requisition, requisition_line,
                                     purchase_id, supplier):
        vals = super(PurchaseRequisition, self)._prepare_purchase_order_line(
            requisition, requisition_line, purchase_id, supplier)
        vals.update({
            'purchase_request_lines':
                [(4, line.id) for line
                 in requisition_line.purchase_request_lines],
        })
        return vals
```

So the returned `vals` contains a fields that only exist once the module `purchase_request_to_rfq` is installed.
From there my solution was to raise the fields into a common module.
If you don't want this field into purchase request maybe a glue module could be made?

**Comment by JonathanNEMRY** [comment]
@jbeficent  looking back a moment I think it is the feature that report `purchase_request` relation from requestion to `purchase_order` that should be moved into a third module. By this way we can keep the new field into `purchase_request_to_rfq` and no more warning with unexisting field when the module is not installed. So it could be something like this:

```
                    purchase_request
                                |
    -------------------------------------------------
   |                                                |
pr_to_rfq                                       pr_to_requisition
   |                                                |
   --------------------------------------------------
                                 |
                      pr_to_req_to_rfq
```

What do your think about this?

**Comment by JordiBForgeFlow** [comment]
Thanks @JonathanNEMRY for your analysis. What I suggest is to make module 'purchase_request_to_requisition' dependent on 'purchase_request_to_rfq'. This will reduce the number of modules that need to be installed, and does not harm to a user of Bids to have the possibility to create RFQ's from Purchase Requests.

On the contrary, some companies do not want to use the Bids.

What do you think?

**Comment by JonathanNEMRY** [comment]
Ok for me. done into the last commit

**Comment by JordiBForgeFlow** [comment]
@JonathanNEMRY Thanks!! The PR is good to merge for me.

**Pull request merged**
