### PR TITLE
Time to change for a new icon

### PR DESCRIPTION
**Pull request by youring**
image

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
Nice! Could you, could you rotate cart basket some angle to the right? It seems a little weird now, sorry for my nitpicking :)

**Comment by youring** [comment]
image
Do you mean like this?

**Review by HviorForgeFlow — APPROVED** [review]
Exactly this :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@youring Could the cross be changed by something else more suitable? I mean, the cross usually means something medical related.

**Comment by youring** [comment]
image
What about this one? Inspired by github pull **request** icon.
Meanwhile, I think the blue cross is simple and acceptable as long as it's not red cross ;)
What's your vote?

**Comment by LoisRForgeFlow** [comment]
@youring What a pity to lost this icon, I think it was a good initiative to update it! Maybe you could open a new PR with only the icon change? I would be glad to approve it and help to get it merge if you ping me.

**Pull request closed without merging**
